"""Formats an AI-styled HTML view of a report, verified against the real one.

A command of its own, run after an audit like `export_reports.py`. It hands the
**deterministic** `report.md` to a local model (gemma by default) and asks it to
lay the same facts out as a styled page. The authoritative `report.html` is
untouched and stays byte-reproducible; this page is an optional presentation.

The danger a security report cannot accept is a model that **invents** a
vulnerability, so a page naming any advisory id (CVE-/GHSA-) the audit never
found is refused whole -- nothing is written -- the way the remediation contract
refuses an answer that breaks its rules. A model also summarises, so it may
**omit** ids; that is not fatal but is not hidden either -- the banner then says
the page is incomplete and points at the authoritative `report.html`.

Non-deterministic by nature (the model re-renders), so `report.ai.html` is a
documented exception to byte-identity, gitignored under `artifacts/`, and never
enters the audit's artifact count.
"""

import argparse
import html
import re
import sys
from pathlib import Path

import config
from reporting import markdown_html
import model_client

REPORT_NAME = "report.md"
AI_REPORT_NAME = "report.ai.html"
AI_REPORT_MODEL = config.get("AUDITOR_AI_REPORT_MODEL")

# Advisory ids are the security content that must not change. CVE and GHSA
# are what Trivy reports today; the other OSV schemes are matched too so a
# fabricated id in any of them is caught, not just the ones one app has.
ADVISORY_ID = re.compile(
    r"\b(?:CVE-\d{4}-\d+"
    r"|GHSA-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}"
    r"|(?:GO|RUSTSEC|PYSEC|OSV)-\d{4}-\d+)\b", re.IGNORECASE)

# A banner the reader meets first, so the page is never mistaken for the source.
COMPLETE_BANNER = ("AI-formatted view — not authoritative. Generated by a local "
                   "model from report.md, the report of record. Verified to "
                   "invent no vulnerability and to name every advisory the audit "
                   "found; presentation may still differ.")
INCOMPLETE_BANNER = ("AI-formatted view — not authoritative and INCOMPLETE. "
                     "Generated by a local model, it omits {n} advisory "
                     "id(s) the audit found and invents none. **See report.html "
                     "for the complete, authoritative report.**")

BANNER_STYLE = ("background:#fde68a;padding:1rem;border-radius:6px;"
                "margin-bottom:1.5rem")

PROMPT = """You are formatting a security audit report as a single clean HTML page.

Rules you MUST follow:
- Use ONLY the facts in the report below. Do not add, remove, invent, or alter
  any finding, CVE id, GHSA id, component, version, severity, or number.
- Every advisory id (CVE-... or GHSA-...) in the report must appear in your HTML,
  and you must introduce none that are not in the report.
- Output a complete HTML document body only (no markdown, no commentary before
  or after). Style it readably with inline CSS; a table for the dependency
  vulnerabilities is welcome.

REPORT:
{report}
"""


def advisory_ids(text: str) -> set[str]:
    """Every distinct CVE/GHSA id mentioned, the tokens the page is verified on."""
    return set(ADVISORY_ID.findall(text))


def _verify(report_md: str, page: str) -> tuple[bool, int]:
    """Refuse a page that INVENTS an advisory; report how many it omitted.

    Invention is fatal -- a fabricated vulnerability is the worst failure a
    security report has, so a page naming a CVE the audit never found is
    refused whole. Omission is not fatal but is not hidden: the count is
    returned so the banner can say the page is incomplete and point at the
    authoritative `report.html`. A model summarises, so an omission is expected;
    a fabrication never is.
    """
    expected, got = advisory_ids(report_md), advisory_ids(page)
    invented = got - expected
    if invented:
        raise ValueError(
            f"the model's page names advisories the audit never found and was "
            f"refused: {sorted(invented)}")
    dropped = len(expected - got)
    return dropped == 0, dropped


def _provenance(digest: str | None) -> str:
    """One line naming the model that wrote the page, so its origin is on the page."""
    short = digest.split(":", 1)[-1][:12] if digest else None
    build = f", build `{short}`" if short else ", build not recorded"
    return f"Formatted by `{AI_REPORT_MODEL}`{build}."


def build_page(report_md: str) -> str:
    """Ask the model to format the report, verify it, and wrap it as a page.

    Raises RuntimeError when the model cannot be reached (the caller degrades),
    ValueError when the model's output fails verification.
    """
    answer = model_client.ask(PROMPT.format(report=report_md), model=AI_REPORT_MODEL)
    body = _strip_fence(answer)
    complete, dropped = _verify(report_md, body)
    banner = COMPLETE_BANNER if complete else INCOMPLETE_BANNER.format(n=dropped)
    digest = _safe_digest()
    header = (f'<div style="{BANNER_STYLE}"><strong>{html.escape(banner)}'
              f'</strong><br><small>{html.escape(_provenance(digest))}'
              "</small></div>")
    return markdown_html.wrap_page(header + body, "Audit report (AI-formatted)")


def _strip_fence(answer: str) -> str:
    """Drop a leading ```html fence if the model wrapped its output in one."""
    text = answer.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[-1]
        text = text.rsplit("```", 1)[0]
    return text.strip()


def _safe_digest() -> str | None:
    """The model's digest, or None when the listing cannot be read -- never fatal."""
    try:
        return model_client.model_digest(AI_REPORT_MODEL)
    except RuntimeError:
        return None


def format_report(app_dir: Path) -> Path:
    """Write the AI-formatted page beside the report it is built from."""
    if not app_dir.is_dir():
        raise NotADirectoryError(f"cannot read {app_dir}: not a directory")
    source = app_dir / REPORT_NAME
    if not source.is_file():
        raise FileNotFoundError(f"no {REPORT_NAME} in {app_dir}; run the audit first")
    page = build_page(source.read_text(encoding="utf-8"))
    target = app_dir / AI_REPORT_NAME
    target.write_text(page, encoding="utf-8")
    return target


def build_parser() -> argparse.ArgumentParser:
    """Describe the command line arguments."""
    parser = argparse.ArgumentParser(
        description="Format an AI-styled HTML view of an audit report (optional).")
    parser.add_argument("app_dir", type=Path, help="an app's artifact directory")
    return parser


def main() -> int:
    """Format one report. Returns the process exit code."""
    args = build_parser().parse_args()
    try:
        written = format_report(args.app_dir)
    except RuntimeError as error:
        # The model could not be reached: degrade, like remediation does.
        print(f"  no AI report: {error}", file=sys.stderr)
        return 0
    except (NotADirectoryError, FileNotFoundError, ValueError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(f"wrote {written}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
